version: '3.3'

services:
  cockpit-nas-agent:
    build: .
    container_name: cockpit-nas-agent
    privileged: true
    security_opt:
      - apparmor:unconfined
    restart: always
    network_mode: host
    environment:
      DB_URL: "http://192.168.188.22:3001"
      HOSTNAME: "NAS-Jannik"
      INTERVAL: "15"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /volume1:/volume1:ro
